# Copyright (c) 2026 FZI Forschungszentrum Informatik
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#    * Neither the name of the copyright holder nor the names of its
#      contributors may be used to endorse or promote products derived from
#      this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: ((trees/)|(html/))
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
        exclude: ((trees/)|(html/))
      - id: end-of-file-fixer
        exclude: ((trees/)|(html/)|(testdata/))
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ((trees/)|(html/)|(testdata/))
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker # Forbid UTF-8 byte-order markers
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
        args: [--config=ros_bt_py/pyproject.toml]
      - id: ruff-format
        args: [--config=ros_bt_py/pyproject.toml]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        exclude: |
          (?x)(
            html/|
            Makefile
          )
      - id: forbid-tabs
        exclude: |
          (?x)(
            html/|
            Makefile
          )
      - id: insert-license
        name: Add license header (Python, CMake, YAML)
        args:
          - --license-filepath=LICENSE
          - --comment-style=#
          - --no-extra-eol
          - --allow-past-years
          - --use-current-year
        types_or: [python, cmake, yaml]
        exclude: ros_bt_py/ros_bt_py/vendor/
      - id: insert-license
        name: Add license header (ROS interfaces)
        args:
          - --license-filepath=LICENSE
          - --comment-style=#
          - --no-extra-eol
          - --allow-past-years
          - --use-current-year
        files: \.(msg|srv|action)$
        exclude: ros_bt_py/ros_bt_py/vendor/
      - id: insert-license
        name: Add license header (XML)
        args:
          - --license-filepath=LICENSE
          - --comment-style=<!--||-->
          - --no-extra-eol
          - --insert-license-after-regex=<\?xml-model
          - --allow-past-years
          - --use-current-year
        types: [xml]
        exclude: ros_bt_py_web_gui/html/
